# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lend',
            name='name',
        ),
    ]
