# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('money', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('lend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owe', to='lend.Lend')),
            ],
        ),
    ]
