# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owe',
            name='money',
            field=models.IntegerField(),
        ),
    ]
