# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owe', '0002_auto_20170806_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owe',
            name='name',
        ),
    ]
